package loanbook.ui.testutil;

import static org.junit.Assert.assertEquals;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.stream.Collectors;

import guitests.guihandles.BikeCardHandle;
import guitests.guihandles.LoanCardHandle;
import guitests.guihandles.LoanListPanelHandle;
import guitests.guihandles.ResultDisplayHandle;
import loanbook.model.bike.Bike;
import loanbook.model.loan.Loan;
import loanbook.model.tag.Tag;
import loanbook.ui.LoanCard;

/**
 * A set of assertion methods useful for writing GUI tests.
 */
public class GuiTestAssert {
    private static final String LABEL_DEFAULT_STYLE = "label";

    /**
     * Asserts that {@code actualCard} displays the same values as {@code expectedCard}.
     */
    public static void assertBikeCardEquals(BikeCardHandle expectedCard, BikeCardHandle actualCard) {
        assertEquals(expectedCard.getId(), actualCard.getId());
        assertEquals(expectedCard.getName(), actualCard.getName());
    }

    /**
     * Asserts that {@code actualCard} displays the same values as {@code expectedCard}.
     */
    public static void assertLoanCardEquals(LoanCardHandle expectedCard, LoanCardHandle actualCard) {
        assertEquals(expectedCard.getId(), actualCard.getId());
        assertEquals(expectedCard.getEmail(), actualCard.getEmail());
        assertEquals(expectedCard.getName(), actualCard.getName());
        assertEquals(expectedCard.getNric(), actualCard.getNric());
        assertEquals(expectedCard.getBike(), actualCard.getBike());
        assertEquals(expectedCard.getPhone(), actualCard.getPhone());
        assertEquals(expectedCard.getLoanRate(), actualCard.getLoanRate());
        assertEquals(expectedCard.getLoanStartTime(), actualCard.getLoanStartTime());
        assertEquals(expectedCard.getTags(), actualCard.getTags());

        expectedCard
                .getTags()
                .forEach(tag ->
                        assertEquals(expectedCard.getTagStyleClasses(tag), actualCard.getTagStyleClasses(tag)));
    }

    /**
     * Asserts that {@code actualCard} displays the details of {@code expectedBike}.
     */
    public static void assertCardDisplaysBike(Bike expectedBike, BikeCardHandle actualCard) {
        assertEquals(expectedBike.getName().value, actualCard.getName());
    }

    /**
     * Asserts that {@code actualCard} displays the details of {@code expectedLoan}.
     */
    public static void assertCardDisplaysLoan(Loan expectedLoan, LoanCardHandle actualCard) {
        assertEquals(expectedLoan.getName().value, actualCard.getName());
        assertEquals(expectedLoan.getNric().getCensored(), actualCard.getNric());
        assertEquals(expectedLoan.getPhone().getCensored(), actualCard.getPhone());
        assertEquals(expectedLoan.getEmail().getCensored(), actualCard.getEmail());
        assertEquals(expectedLoan.getBike().getName().value, actualCard.getBike());
        assertEquals(expectedLoan.getLoanRate().toString(), actualCard.getLoanRate());
        assertTagsEqual(expectedLoan, actualCard);
    }

    /**
     * Returns the color style for {@code tagName}'s label. The tag's color is determined by looking up the color
     * in {@code LoanCard#TAG_COLOR_STYLES}, using an index generated by the hash code of the tag's content.
     *
     * @see LoanCard#getTagColorStyleFor(String)
     */
    private static String getTagColorStyleFor(String tagName) {
        switch (tagName) {
        case "owesMoney":
        case "colleagues":
        case "classmates":
        case "neighbours":
        case "family":
        case "friend":
        case "friends":
        case "husband":
            return "brown";
        case "Ongoing":
            return "orange";
        case "Returned":
            return "green";
        case "Deleted":
            return "red";
        default:
            throw new AssertionError(tagName + " does not have a color assigned.");
        }
    }

    /**
     * Asserts that the tags in {@code actualCard} matches all the tags in {@code expectedPerson} with the correct
     * color.
     *
     */
    private static void assertTagsEqual(Loan expectedLoan, LoanCardHandle actualCard) {
        HashSet<Tag> newTags = new HashSet<>(expectedLoan.getTags());
        newTags.add(new Tag(expectedLoan.getLoanStatus().toString()));
        List<String> expectedTags = newTags.stream()
                .map(tag -> tag.value).collect(Collectors.toList());
        assertEquals(expectedTags, actualCard.getTags());
        expectedTags.forEach(tag -> assertEquals(
                Arrays.asList(LABEL_DEFAULT_STYLE, getTagColorStyleFor(tag)),
                actualCard.getTagStyleClasses(tag)
        ));
    }

    /**
     * Asserts that the list in {@code loanListPanelHandle} displays the details of {@code loans} correctly and
     * in the correct order.
     */
    public static void assertListMatching(LoanListPanelHandle loanListPanelHandle, Loan... loans) {
        for (int i = 0; i < loans.length; i++) {
            loanListPanelHandle.navigateToCard(i);
            assertCardDisplaysLoan(loans[i], loanListPanelHandle.getCardHandle(i));
        }
    }

    /**
     * Asserts that the list in {@code loanListPanelHandle} displays the details of {@code loans} correctly and
     * in the correct order.
     */
    public static void assertListMatching(LoanListPanelHandle loanListPanelHandle, List<Loan> loans) {
        assertListMatching(loanListPanelHandle, loans.toArray(new Loan[0]));
    }

    /**
     * Asserts the size of the list in {@code loanListPanelHandle} equals to {@code size}.
     */
    public static void assertListSize(LoanListPanelHandle loanListPanelHandle, int size) {
        int numberOfLoans = loanListPanelHandle.getListSize();
        assertEquals(size, numberOfLoans);
    }

    /**
     * Asserts the message shown in {@code resultDisplayHandle} equals to {@code expected}.
     */
    public static void assertResultMessage(ResultDisplayHandle resultDisplayHandle, String expected) {
        assertEquals(expected, resultDisplayHandle.getText());
    }
}
