= LoanBook - User Guide
:site-section: UserGuide
:toc: left
:toc-title: UserGuide
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S1-F10-2/main

By: `Team F10-2`      Since: `Sep 2018`      Licence: `MIT`

== Introduction

Have you ever seen your clients waiting angrily for 15 minutes before finally getting their rental bikes? Introducing Forever A-Loan, a lightweight Command Line Interface (CLI) application that revolutionizes the way bike loans are logged. Forever A-Loan promises to drastically decrease the time taken for bike rental shop owners to manage their inventories by leveraging on state of the art inventory management algorithms and the absence of a clunky Graphical User Interface (GUI) that hinders fast typists. Enjoy!

== Quick Start

.  Ensure you have Java version `9` or later installed in your computer.
.  Download the latest `LoanBook.jar` link:{repoURL}/releases[here].
.  Run the .jar file. The GUI should appear in a few seconds.
.  Type the command in the command box and press kbd:[ENTER] to execute it. +
e.g. typing *`help`* and pressing kbd:[ENTER] will open the help window.
.  Some example commands you can try:

* *`list`* : List the status of the loanbook
* **`add`**`p/John hp/12345678 e/john@abc.com r/3 o/Bicycle-007` : Loans Bicycle-007 to John at a rate of $3 per hour
* **`delete`**`i/1 x/a12345` : deletes the 1st loan shown in the current list
* *`reset`* : Reset the loanbook

[NOTE]
The default password for the app is `a12345`. This is required for some commands such as `reset` and `delete`.

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add o/OBJECT_NAME`, `OBJECT_NAME` is a parameter which can be used as `add o/Bicycle`.
* All parameters need to be specified in order for the command to work, unless they are in square brackets. e.g. in `add n/LOANER_NAME [t/TAGS]`, `LOANER_NAME` must be specified, but `TAGS` can be left out.
* Parameters can be specified in any order.
* Command words are case-sensitive and should be in all lowercase. Most parameters are case-sensitive too.
* If you enter the parameters of a command incorrectly, the LoanBook will feedback the correct command format to you.
====

=== Viewing help: `help`

Provides a list of all commands together with a basic description, how-to-use and example usage for each command. +

[NOTE]
This will cause a pop-up window to appear, containing a copy of this User Guide.

[TIP]
This is not the only way to get help! If you key in the commands with the wrong format, you will get a prompt in the display box which will give you a brief description of the command. It will also tell you how to use the command correctly.

Format: `help`

=== Adding a bike: `addbike`

Adds a bike to the loan book with the following parameters, and displays the bike's details as confirmation. +
Format: `addbike n/BIKE_NAME`

[NOTE]
`BIKE_NAME` is used as a bicycle identifier, that is, every bicycle should have a unique bicycle name. As such, `BIKE_NAME` will be rejected if it matches the name of an existing bike in the LoanBook.

Examples:

* `addbike n/A Wonderful Bike`
* `addbike n/BX-0027`

=== Adding a loan: `add`

Adds a loan to the loan book with the following parameters, and displays the transaction along with a LOAN_ID to keep track of the loan. +
Format: `add n/NAME ic/NRIC p/PHONE e/EMAIL b/BIKE lr/LOANRATE [t/TAG]...`

[NOTE]
PERSON_PHONE_NO and PERSON_EMAIL should not be blank. +
BIKE_NAME must be the name of a bicycle that has already been registered into the LoanBook. +
NUMBER_LOANED and LOAN_OUT_PERIOD must be a positive integer. +
LOANRATE is in dollars per hour.

Examples:

* `add n/John Doe ic/T0248272F p/98765432 e/johnd@example.com b/Bike001 lr/3.5 t/friends t/owesMoney`
* `add n/James Ho ic/T0248272F p/91234567 e/jamesh@example.com b/Bike001 lr/3.5`

[TIP]
====
The best part about this is you do not even need to key in the time that you created this loan! LoanBook does the timing for you! Simple isn't it?
====

=== Listing all bikes: `listbikes`

Shows a list of all registered bicycles in the LoanBook. +
Format: `listbikes`

=== Listing all loans: `list`

Shows a list of all loans in the LoanBook. +
Format: `list`

=== [Coming in v1.4] Editing a bike : `editbike`

To keep the system updated with any changes in the bicycles, this command allows details of a bicycle to be edited. +
Format: `edit BIKE_NAME [n/NEW_BIKE_NAME]`

* At least one of the optional fields must be provided.
* Existing values will be updated to the input values. Any values not specified in the command will be unchanged.

Examples:

* `edit Bike 1 n/Bike-001` +
For the bicycle named "Bike 1", its name is changed to "Bike-001", as long as "Bike-001" isn't already the name of another registered bicycle.

=== Editing a loan: `edit`

In case a wrong entry is keyed in, or the customer changes their mind, this command allows details of a loan entry to be edited. +
Format: `edit INDEX (must be a positive integer) [n/NAME] [ic/NRIC] [p/PHONE] [e/EMAIL] [b/BIKE] [lr/LOANRATE] [t/TAG]...`

****
* Edits the loan at the specified `LOAN_INDEX`. This LOAN_INDEX refers to the LOAN_INDEX number shown in the displayed loan list. The LOAN_INDEX *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the loan will be removed i.e adding of tags is not cumulative.
****

Examples:

* `edit 1 p/91234567 e/johndoe@example.com` +
For the loan at index 1, changes the loaned object from whatever it was before to Bicycle-017.
* `edit 1 n/James Tan p/90010090 e/jamest@example.com lr/144` +
For the loan at index 1, changes the customer to James Tan, who has the specified contact details, to the rate of $144 per hour.

[NOTE]
====
We do not allow editing of the loan's start time or the return time because we want you to be able to use our application as an auditing tool. We hope that this can then simplify the management of your business.
====

=== Locating loans by keywords: `find`

Finds loans whose customers' names contain any of the given keywords. +
Format: find KEYWORD [MORE_KEYWORDS]

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Loans matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****

Examples:

* `find John` +
Returns `john` and `John Doe`
* `find Betsy Tim John` +
Returns any loan having names `Betsy`, `Tim`, or `John`

=== [Coming in v1.4] Deleting the chosen bike from the loan book : `deletebike`

Deletes a bike from the loan book. +
Format: `deletebike BIKE_NAME x/CURRENT_PASSWORD`

[NOTE]
The command will be rejected if there are any ongoing loans that use that bicycle. Return or delete those loans first.

Examples:

* `delete Bike 1 x/a12345` +
Deletes the bicycle with the name of "Bike 1".

=== Deleting the chosen loan from the loan book: `delete`

Delete the loan from the loan book. If you want to delete one loan, use `delete i/LOAN_INDEX x/CURRENT_PASSWORD`.
Due to `delete` modifying transactional summary, it is a critical command and hence elevation is required hence the password field. +
Format: `delete i/LOAN_INDEX x/CURRENT_PASSWORD`

****
* Deletes the loan at the specified `i/LOAN_INDEX`.
* Note that this does not reset `LOAN_ID`.
* Deletion will not occur if `CURRENT_PASSWORD` is incorrect.
****

[NOTE]
====
The default password for the app is `a12345`.
====

Examples:

* `delete i/1 x/a12345` +
Deletes the loan with that has been indexed at position 1.

// tag::setpass[]
=== Changing the password of the app: `setpass`

Change the current password of the app to `NEW_PASSWORD`. This ensures that critical commands such as `delete` and `reset` may be performed by authorized personnel only. +
Format: `setpass CURRENT_PASSWORD NEW_PASSWORD`

****
* Set the password of the app to `NEW_PASSWORD`
* Password change will not occur if `CURRENT_PASSWORD` is incorrect.
****

Examples:

* `setpass a12345 n3wP4sS` +
Set the password of the app to `n3wP4sS`.
// end::setpass[]

=== Returning a loan: `return`

What's the use of a LoanBook if you are unable to return the loans that you have? This is how you can do that! In fact, we see your pains trying to calculate the amount payable on a calculator, so we decided to help you out by doing all the number crunching for you.

This command marks a loan as returned based on LOAN_INDEX and automatically prints out the amount payable. The amount payable will be prorated and rounded down to the nearest minute. +

[TIP]
====
We choose to do this because when we get down to seconds, the difference in the earnings you will get is going to be on the order of a fraction of cents. We hope that by doing this, your business would not seem to be very petty about the money.

Also, this would be good for your business, as customers will not feel that they have been ripped off the cost of renting a bike for an extra minute just because you took 5 seconds to log their return details! :)
====

Do note that you will have to list out all the loans in order, or search for a particular loan that you would like to return. From there, you need to key in the index number of the loan as a parameter into this command.

Format: `return i/LOAN_INDEX`

[NOTE]
Do be careful to note that it is the loan INDEX that you are keying into the program. Please do not key in the LoanID instead!

[WARNING]
====
This command is currently not undoable. Please be careful to double check.

We are working on fixing this issue! Do look forward to seeing this new functionality in the next release of LoanBook, version 2.0!
====

Examples:

* `return i/1` +
Marks the loan that has been indexed at position 1 as returned. Also automatically prints out the amount payable based on loan time and rate.

// tag::searchcommand[]
=== Locating loans by date of loan: `search`

Returns all loans that were created between the range provided
Format: `search START_DATE END_DATE`

****
* Date format must be YYYY-MM-DD.
* The search is format sensitive sensitive. i.e. Date format must be strictly followed`.
* The search is determined on the date and time of loan created.
* Date provided must be valid. i.e. 2018-02-31 will return an error as it is not a valid date.
* The start date provided should be before end date. i.e. `search 2018-01-02 2018-01-01` will throw an error.
****

Examples:

* `search 2018-01-01 2018-01-01` +
Searches for loans with loan start date and time as 2018-01-01.
* `search 2018-01-01 2018-01-02` +
Searches for loans with loan start date and time between 2018-01-01 and 2018-01-02, inclusive.
// end::searchcommand[]

=== Hard reset the entire loan book : `reset`

Removes all the loans from the loan book and resets the LOAN_ID counter. +
Format: `reset`

[NOTE]
====
The difference between deleting all the loans and hard resetting the LoanBook is that when a loan is deleted, you will still be able to search for it. However, the statistics of deleted loans do not appear in the `summary` command.
====

[WARNING]
====
**Hard resetting the LoanBook will remove ALL loans! Do this ar your own peril.**
====

=== Summarize all the transactions: `summary`

Do you want to find out at a glance how much money your business has collected? Or maybe out of all the bicycles you have, how many are currently loaned out? Here's the command for you.

This feature shows the total number of loans that are done and in progress. It also summarizes the loan status of each item, the number of times an object was loaned before.

The `summary` function would display the statistics of all your loans in the display box on the right of the application. There, you will find the following statistics:

* Total number of ongoing loans
* Total number of loans ever taken out
* Total amount of time all bikes have been loaned for
* Total revenue from the loan service

Format: `summary`

[NOTE]
====
The summary feature may take a while to run, especially when you have many loans that you have made in the past. Please allow about a second for it to process.
====

=== Listing entered commands: `history`

Lists all the commands that you have entered in reverse chronological order. +
Format: `history`

[NOTE]
====
Pressing the kbd:[&uarr;] and kbd:[&darr;] arrows will display the previous and next input respectively in the command box.
====

=== Check your email: `checkemail`

Checks whether you have set your email or not, and displays the censored email address if you have set it before. +
Format: `checkemail`

=== Set your email: `setemail`

Sets the email address to send reminder emails from. +
Format: `setemail OLDEMAIL NEWEMAIL`

* `OLDEMAIL` is `default` if you have not set an email yet.
* `OLDEMAIL` must be the same as the one you set last time.
* `NEWEMAIL` cannot the same as `OLDEMAIL`.
* `NEWEMAIL` must be a valid Gmail address.

[NOTE]
Only Gmail is accepted!

Examples:

* `setemail default \new_email@gmail.com`
* `setemail \old_email@gmail.com \new_email@gmail.com`

=== Send reminder email: `remind`

Sends a reminder email to the customer. +
Format: `remind x/EMAILPASSWORD n/NAME b/BIKE`

* `NAME` and `BIKE` must be from the same `ONGOING` loan.
* `EMAILPASSWORD` must be correct.

[NOTE]
*[IMPORTANT] Before using this command, please go to* https://www.google.com/settings/security/lesssecureapps[Less Secure Apps] *, enable it and refresh the Settings page!*

Examples:

* `remind x/123456 n/Alex b/Bike001`
* `remind x/nscjhbdhv n/Peter Lee b/NewBike`

////
// tag::undoredo[]
=== Undoing previous command: `undo`

Restores the address book to the state before the previous _undoable_ command was executed. +
Format: `undo`

[NOTE]
====
Undoable commands: those commands that modify the address book's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `delete 1` +
`list` +
`undo` (reverses the `delete 1` command) +

* `select 1` +
`list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

=== Redoing the previously undone command : `redo`

Reverses the most recent `undo` command. +
Format: `redo`

Examples:

* `delete 1` +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +

* `delete 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

=== Clearing all entries: `clear`

Clears all entries from the address book. +
Format: `clear`

=== Exiting the program: `exit`

Exits the program. +
Format: `exit`

=== Saving the data

Address book data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

// tag::dataencryption[]
=== Encrypting data files `[coming in v2.0]`

_{explain how the user can enable/disable data encryption}_
// end::dataencryption[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Add* `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...` +
e.g. `add n/James Ho p/90224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague`
* *Clear* : `clear`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Edit* : `edit INDEX [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [t/TAG]...` +
e.g. `edit 2 n/James Lee e/jameslee@example.com`
* *Find* : `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find James Jake`
* *List* : `list`
* *Help* : `help`
* *Select* : `select INDEX` +
e.g.`select 2`
* *History* : `history`
* *Undo* : `undo`
* *Redo* : `redo`
////
