= LoanBook - User Guide
:site-section: UserGuide
:toc: left
:toc-title: UserGuide
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S1-F10-2/main

By: `Team F10-2`      Since: `Sep 2018`      Licence: `MIT`

== Introduction

Ever wanted to start up your business, only to realise that managing your inventories is a clumpy chore. Current available inventories management softwares such as as MYOB is expensive and does not offer useful features to small scale businesses. Introducing WFIDX, the new revolutionary command line application that promises to revolutionise how the SME industry manages inventories. Minimizing the clunky Graphical User Interface (GUI) that hinders fast typist, WFIDX promises to decrease the time taken for businesses to manage their inventories than before by using CLI. Enjoy!

== Quick Start

.  Ensure you have Java version `9` or later installed in your computer.
.  Download the latest `LoanBook.jar` link:{repoURL}/releases[here].
.  Run the .jar file. The GUI should appear in a few seconds.
.  Type the command in the command box and press kbd:[ENTER] to execute it. +
e.g. typing *`help`* and pressing kbd:[ENTER] will open the help window.
.  Some example commands you can try:

* *`list`* : List the status of the loanbook
* **`add`**`p/John hp/12345678 e/john@abc.com r/3 o/Bicycle-007` : Loans Bicycle-007 to John at a rate of $3 per hour
* **`delete`**`3` : deletes the 3rd loan shown in the current list
* *`reset`* : Reset the loanbook

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add o/OBJECT_NAME`, `OBJECT_NAME` is a parameter which can be used as `add o/Bicycle`.
====

=== Viewing help : `help`

Provides a list of all commands together with a basic description, how-to-use and example usage for each +
Format: `help`

=== Adding a loan: `add`

Adds a loan to the loan book with the following parameters, and displays the transaction along with a Loan ID to keep track of the loan +
Format: `add p/PERSON_NAME hp/PERSON_PHONE_NO e/PERSON_EMAIL r/RATE o/OBJECT_IDENTITY`

[TIP]
NUMBER_LOANED and LOAN_OUT_PERIOD must be a positive integer
RATE is in dollars per hour.
PERSON_PHONE_NO and PERSON_EMAIL should not be blank.

Examples:

* `add p/John hp/97626753 e/johnw@abc.com r/5 o/Bicycle-007`
* `add p/James Tan hp/86661352 e/alabaaoe@xyz.com r/144 o/Bicycle-007`

=== Listing all loans : `list`

Shows a list of all loans in the loan book. +
Format: `list`

=== Editing a loan : `edit`

In case a wrong entry is keyed in, or the customer changes their mind, this command allows details of a loan entry to be edited. +
Format: `edit i/LOAN_ID [p/PERSON_NAME] [hp/PERSON_PHONE_NO] [e/PERSON_EMAIL] [r/RATE] [o/OBJECT_IDENTITY]`

****
* Edits the person at the specified `LOAN_ID`. The index refers to the index number shown in the displayed person list. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the person will be removed i.e adding of tags is not cumulative.
****

Examples:

* `edit i/11037 o/Bicycle-017` +
For the loan with Loan ID 11037, changes the loaned object from whatever it was before to Bicycle-017.
* `edit i/90210 p/James Tan hp/86661352 e/alabaaoe@xyz.com r/144` +
For the loan with Loan ID 90210, changes the customer to James Tan, who has the specified contact details, to the rate of $144 per hour.

=== Locating loans by key words: `search`

Returns a loan based on parameters of LOAN_ ID, PERSON_NAME or OBJECT_IDENTITY. +
Format: `search [i/LOAN_ID] [p/PERSON_NAME] [o/OBJECT_IDENTITY]`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only full words will be matched e.g. `Han` will not match `Hans`
* Loans matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****

Examples:

* `search i/11037` +
Searches for the loan with Loan ID 11037
* `search p/James Tan` +
Searches for loans made by James Tan
* `search p/John Doe o/Bicycle-007` +
Searches for loans made by John Doe where the item loaned out is Bicycle-007

=== Deleting the chosen loan from the loan book : `delete`

Delete the loan from the loan book. If you want to delete one loan, use `delete i/LOAN_ID`. If you want to delete all, use`delete!` +
Format: `delete i/LOAN_ID` or `delete!`

****
* Deletes the loan at the specified `i/LOAN_ID`.
* Note that this does not reset the `i/LOAN_ID`.
****

Examples:

* `delete i/11037` +
Deletes the loan with Loan ID 11037.
* `delete!` +
Deletes all loan records.

=== Returning a loan : `return`

Marks a loan as returned based on LOAN_ ID and automatically prints out the amount payable. +
Format: `return i/LOAN_ID`

Examples:

* `return i/11037` +
Marks the loan with Loan ID 11037 as returned. Also automatically prints out the amount payable based on loan time and rate.

=== Hard reset the entire loan book : `reset`

Removes all the loans from the loan book and resets the LOAN_ID counter. +
Format: `reset`

=== Summarize all the transactions : `summary`

Show the total number of loans that are done and in progress. Also summarizes the loan status of each item, the number of times an object was loaned before. +
Format: `summary`

=== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order. +
Format: `history`

[NOTE]
====
Pressing the kbd:[&uarr;] and kbd:[&darr;] arrows will display the previous and next input respectively in the command box.
====

=== Non-functional features :
* Aliases to allow users to use the CLI with less keystrokes.
* Chainable commands. I.e. allow adding and deleting of items asynchronously.
** `add_items i/bicycle q/5 delete_items motorbike q/7`
* Auto complete
** Populate recently loaned items/users, depending on the input. i.e. add i/ should show a dropdown on the last 5 items used. User can type add i/5 to select the 5th LRU item.
** typing `del` followed by tab auto completes to `delete`
* Send reminder email to the borrower after a day of borrowing reminding them to return the bike.
* Login authentication to ensure that some other bugger don't delete the loan stuffs. Require password when deleting.

////
// tag::undoredo[]
=== Undoing previous command : `undo`

Restores the address book to the state before the previous _undoable_ command was executed. +
Format: `undo`

[NOTE]
====
Undoable commands: those commands that modify the address book's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `delete 1` +
`list` +
`undo` (reverses the `delete 1` command) +

* `select 1` +
`list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

=== Redoing the previously undone command : `redo`

Reverses the most recent `undo` command. +
Format: `redo`

Examples:

* `delete 1` +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +

* `delete 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

=== Clearing all entries : `clear`

Clears all entries from the address book. +
Format: `clear`

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

Address book data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

// tag::dataencryption[]
=== Encrypting data files `[coming in v2.0]`

_{explain how the user can enable/disable data encryption}_
// end::dataencryption[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Add* `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...` +
e.g. `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague`
* *Clear* : `clear`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Edit* : `edit INDEX [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [t/TAG]...` +
e.g. `edit 2 n/James Lee e/jameslee@example.com`
* *Find* : `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find James Jake`
* *List* : `list`
* *Help* : `help`
* *Select* : `select INDEX` +
e.g.`select 2`
* *History* : `history`
* *Undo* : `undo`
* *Redo* : `redo`
////
