= LoanBook - User Guide
:site-section: UserGuide
:toc: left
:toc-title: UserGuide
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S1-F10-2/main

By: `Team F10-2`      Since: `Sep 2018`      Licence: `MIT`

== Introduction

Have you ever seen your clients waiting angrily for 15 minutes before finally getting their rental bikes? Introducing Forever A-Loan, a lightweight Command Line Interface (CLI) application that revolutionizes the way bike loans are logged. Forever A-Loan promises to drastically decrease the time taken for bike rental shop owners to manage their inventories by leveraging on state of the art inventory management algorithms and the absence of a clunky Graphical User Interface (GUI) that hinders fast typists. Enjoy!

== Quick Start

.  Ensure you have Java version `9` or later installed in your computer.
.  Download the latest `LoanBook.jar` link:{repoURL}/releases[here].
.  Run the .jar file. The GUI should appear in a few seconds.
.  Type the command in the command box and press kbd:[ENTER] to execute it. +
e.g. typing *`help`* and pressing kbd:[ENTER] will open the help window.
.  Some example commands you can try:

* *`list`* : List the status of the loanbook
* **`add`**`p/John hp/12345678 e/john@abc.com r/3 o/Bicycle-007` : Loans Bicycle-007 to John at a rate of $3 per hour
* **`delete`**`3` : deletes the 3rd loan shown in the current list
* *`reset`* : Reset the loanbook

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add o/OBJECT_NAME`, `OBJECT_NAME` is a parameter which can be used as `add o/Bicycle`.
====

=== Viewing help : `help`

Provides a list of all commands together with a basic description, how-to-use and example usage for each command. +

[NOTE]
This will cause a pop up window to appear, containing a copy of this User Guide.

[TIP]
This is not the only way to get help! If you key in the commands with the wrong format, you will get a prompt in the display box which will give you a brief description of the command. It will also tell you how to use the command correctly.

Format: `help`

=== Adding a loan: `add`

Adds a loan to the loan book with the following parameters, and displays the transaction along with a LOAN_ID to keep track of the loan. +
Format: `add p/PERSON_NAME hp/PERSON_PHONE_NO e/PERSON_EMAIL r/RATE o/OBJECT_IDENTITY`

[NOTE]
NUMBER_LOANED and LOAN_OUT_PERIOD must be a positive integer
RATE is in dollars per hour.
PERSON_PHONE_NO and PERSON_EMAIL should not be blank.

Examples:

* `add p/John hp/97626753 e/johnw@abc.com r/5 o/Bicycle-007`
* `add p/James Tan hp/86661352 e/alabaaoe@xyz.com r/144 o/Bicycle-007`

[TIP]
====
The best part about this is you do not even need to key in the time that you created this loan! LoanBook does the timing for you! Simple isn't it?
====

=== Listing all loans : `list`

Shows a list of all loans in the LoanBook. +
Format: `list`

=== Editing a loan : `edit`

In case a wrong entry is keyed in, or the customer changes their mind, this command allows details of a loan entry to be edited. +
Format: `edit i/LOAN_INDEX [p/PERSON_NAME] [hp/PERSON_PHONE_NO] [e/PERSON_EMAIL] [r/RATE] [o/OBJECT_IDENTITY]`

****
* Edits the loan at the specified `LOAN_INDEX`. This LOAN_INDEX refers to the LOAN_INDEX number shown in the displayed loan list. The LOAN_INDEX *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the loan will be removed i.e adding of tags is not cumulative.
****

Examples:

* `edit i/11 o/Bicycle-017` +
For the loan at index 11, changes the loaned object from whatever it was before to Bicycle-017.
* `edit i/9 p/James Tan hp/86661352 e/alabaaoe@xyz.com r/144` +
For the loan at index 9, changes the customer to James Tan, who has the specified contact details, to the rate of $144 per hour.

[NOTE]
====
We do not allow editing of the loan's start time or the return time because we want you to be able to use our application as an auditing tool. We hope that this can then simplify the management of your business.
====

=== Locating loans by key words: `search`

Returns a loan based on parameters of LOAN_INDEX, PERSON_NAME or OBJECT_IDENTITY. +
Format: `search [i/LOAN_INDEX] [p/PERSON_NAME] [o/OBJECT_IDENTITY]`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only full words will be matched e.g. `Han` will not match `Hans`
* Loans matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****

Examples:

* `search i/11037` +
Searches for the loan with LOAN_INDEX 11037
* `search p/James Tan` +
Searches for loans made by James Tan
* `search p/John Doe o/Bicycle-007` +
Searches for loans made by John Doe where the item loaned out is Bicycle-007

=== Deleting the chosen loan from the loan book : `delete`

Delete the loan from the loan book. If you want to delete one loan, use `delete i/LOAN_INDEX x/CURRENT_PASSWORD`.
Due to `delete` modifying transectional summery, it is a critical command and hence elevation is required hence the password field. +
Format: `delete i/LOAN_INDEX x/CURRENT_PASSWORD`

****
* Deletes the loan at the specified `i/LOAN_INDEX`.
* Note that this does not reset `LOAN_ID`.
* Deletion will not occur if `CURRENT_PASSWORD` is incorrect.
****

[NOTE]
====
The default password for the app is `a12345`.
====

Examples:

* `delete i/11037 x/a12345` +
Deletes the loan with that has been indexed at position 11037.

=== Changing the password of the app: `setpass`

Change the current password of the app to `NEW_PASSWORD`. This ensures that critical commands such as `delete` and `reset` may be performed by authorized personnels only. +
Format: `setpass CURRENT_PASSWORD NEW_PASSWORD`

****
* Set the password of the app to `NEW_PASSWORD`
* Password change will not occur if `CURRENT_PASSWORD` is incorrect.
****

Examples:

* `setpass a12345 n3wP4sS` +
Set the password of the app to `n3wP4sS`.

=== Returning a loan : `return`

What's the use of a LoanBook if you are unable to return the loans that you have? This is how you can do that! In fact, we see your pains trying to calculate the amount payable on a calculator, so we decided to help you out by doing all the number crunching for you.

This command marks a loan as returned based on LOAN_INDEX and automatically prints out the amount payable. The amount payable will be prorated and rounded down to the nearest minute. +

[TIP]
====
We choose to do this because when we get down to seconds, the difference in the earnings you will get is going to be on the order of fraction of cents. We hope that by doing this, your business would not seem to be very petty about the money.

Also, this would be good for your business, as customers will not feel that they have been ripped off the cost of renting a bike for an extra minute just because you took 5 seconds to log their return details! :)
====

Do note that you will have to list out all the loans in order, or search for a particular loan that you would like to return. From there, you need to key in the index number of the loan as a parameter into this command.

Format: `return i/LOAN_INDEX`

[NOTE]
Do be careful to note that it is the loan INDEX that you are keying into the program. Please do not key in the LoanID instead!

[WARNING]
====
This command is currently not undoable. Please be careful to double check.

We are working on fixing this issue! Do look forward to seeing this new functionality in the next release of LoanBook, version 2.0!
====

Examples:

* `return i/11037` +
Marks the loan with LOAN_INDEX 11037 as returned. Also automatically prints out the amount payable based on loan time and rate.

=== Hard reset the entire loan book : `reset`

Removes all the loans from the loan book and resets the LOAN_ID counter. +
Format: `reset`

[NOTE]
====
The difference between deleting all the loans and hard resetting the LoanBook is that when a loan is delete, you will still be able to search for it. However, the statistics of deleted loans do not appear in the `summary` command.
====

[WARNING]
====
**Hard resetting the LoanBook will remove ALL loans! Do this ar your own peril.**
====

=== Summarize all the transactions : `summary`

Do you want to find out at a glance how much money your business has collected? Or maybe out of all the bicycles you have, how many are currently loaned out? Here's the command for you.

This feature shows the total number of loans that are done and in progress. It also summarizes the loan status of each item, the number of times an object was loaned before.

The `summary` function would display the statistics of all your loans in the display box on the right of the application. There, you will find the following statistics:

* Total number of ongoing loans
* Total number of loans ever taken out
* Total amount of time all bikes have been loaned for
* Total revenue from the loan service

Format: `summary`

[NOTE]
====
The summary feature may take a while to run, especially when you have many loans that you have made in the past. Please allow about a second for it to process.
====

=== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order. +
Format: `history`

[NOTE]
====
Pressing the kbd:[&uarr;] and kbd:[&darr;] arrows will display the previous and next input respectively in the command box.
====

=== Non-functional features :
* Aliases to allow users to use the CLI with less keystrokes.
* Chainable commands. I.e. allow adding and deleting of items asynchronously.
** `add_items i/bicycle q/5 delete_items motorbike q/7`
* Auto complete
** Populate recently loaned items/users, depending on the input. i.e. add i/ should show a dropdown on the last 5 items used. User can type add i/5 to select the 5th LRU item.
** typing `del` followed by tab auto completes to `delete`
* Send reminder email to the borrower after a day of borrowing reminding them to return the bike.
* Login authentication to ensure that unauthorised people do not delete the loans which they are not supposed to. Require password when deleting.

////
// tag::undoredo[]
=== Undoing previous command : `undo`

Restores the address book to the state before the previous _undoable_ command was executed. +
Format: `undo`

[NOTE]
====
Undoable commands: those commands that modify the address book's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `delete 1` +
`list` +
`undo` (reverses the `delete 1` command) +

* `select 1` +
`list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

=== Redoing the previously undone command : `redo`

Reverses the most recent `undo` command. +
Format: `redo`

Examples:

* `delete 1` +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +

* `delete 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

=== Clearing all entries : `clear`

Clears all entries from the address book. +
Format: `clear`

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

Address book data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

// tag::dataencryption[]
=== Encrypting data files `[coming in v2.0]`

_{explain how the user can enable/disable data encryption}_
// end::dataencryption[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Add* `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...` +
e.g. `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague`
* *Clear* : `clear`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Edit* : `edit INDEX [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [t/TAG]...` +
e.g. `edit 2 n/James Lee e/jameslee@example.com`
* *Find* : `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find James Jake`
* *List* : `list`
* *Help* : `help`
* *Select* : `select INDEX` +
e.g.`select 2`
* *History* : `history`
* *Undo* : `undo`
* *Redo* : `redo`
////
